// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzvinmtqaasxfnpznpux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6dmlubXRxYWFzeGZucHpucHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTcxNDYsImV4cCI6MjA2NTQ3MzE0Nn0.SAcsv62z6ax2LbxvsH_o_fpxz11m_fHKra4-f4uOqG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);